### ISSUE TITLE
Port to Preact

### ISSUE THREAD

**Issue by roman01la** [functionalcave/code-cool#1]
In order to keep the app structured and open for future extension, but still keep it minimal it would be better to have it written in Preact.

## Requirements
- No JSX (use hyperscript syntax in Preact aka `h("tag or component", props, ...children)`)
- No build step: just drop Preact's prod file into the document and write the app in a single file

**Comment by vvai** [comment]
It seems that I could do this, at least I wish to try!

**Comment by roman01la** [comment]
@vvai Sounds good!

**Comment by roman01la** [comment]
fixed in #3
