### ISSUE TITLE
Allow choosing languages

### ISSUE THREAD

**Issue by roman01la** [functionalcave/code-cool#2]
The app is using _CodeMirror_ as code editor and _highlight.js_ to highlight syntax in a screenshot. Both libraries support a large list of languages. We want to allow selecting a language that is supported in both libraries.

- [CodeMirror language modes](https://codemirror.net/mode/)
- [highlight.js languages](https://highlightjs.org/download/)

## Requirements
- Create UI control that displays current language and lists all available languages
- When a language selected, switch both editor and highlighter in appropriate language mode
- The editor stores last input in `localStorage`, implement language detection to automatically switch language mode on load

_NOTE:_ highlight.js does language detection, one possible way to do this in the app is to paste in the code, initialize highlighting and parse class name which corresponds to detected language name.

**Comment by roman01la** [comment]
Blocked by #1

**Comment by vvai** [comment]
I would like to implement this enhancement

**Comment by roman01la** [comment]
@vvai Go for it!
